apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hackathon.com
    http:
      paths:
      - path: /appointment
        pathType: Prefix
        backend:
          service:
            name: appointment-services-svc
            port:
              number: 80
      - path: /order
        pathType: Prefix
        backend:
          service:
            name: order-services-svc
            port:
              number: 80
      - path: /patient
        pathType: Prefix
        backend:
          service:
            name: patient-services-svc
            port:
              number: 80
