name: Docker Build and deploy to GKE for application-service

on:
  push:
    branches:
      - master  # Trigger on push to the main branch, change if needed

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: application-service/

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Google Cloud SDK
      - name: gcp auth
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Store project ID as a secret in GitHub
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Store the service account key as a secret

      # Step 3: Configure Docker to authenticate with GCP
      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/demo-hackathon/application-service:${{ github.run_number }} .

      # Step 5: Push Docker image to GCP Artifact Registry
      - name: Push Docker image
        run: |
          docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/demo-hackathon/application-service:${{ github.run_number }}

  deploy-gke:
    runs-on: ubuntu-latest
    needs: build_and_push

    defaults:
      run:
        working-directory: application-service/

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Google Cloud SDK
      - name: gcp auth
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Store project ID as a secret in GitHub
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Store the service account key as a secret

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: kubectl apply
        run: |
          sed -i 's/latest/${{ github.run_number }}/g' k8s-manifests/*.yml
          kubectl apply -f k8s-manifests/*.yml


        

      

