name: Terraform Setup and apply

on:
  push:
    branches:
      - master 

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest  # The runner to use

    defaults:
      run:
        working-directory: terraform/

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.0'  # Specify the version of Terraform

      - name: gcp auth
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Store project ID as a secret in GitHub
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Run Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Optionally, apply changes (if necessary)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        if: github.ref == 'refs/heads/master'  # Only apply if on main branch
